### PR TITLE
Improve perf with Array.init

### PR DESCRIPTION
**Pull request by AviAvni**
On my machine the original code best run was
image
Array init best result is
image
also the with ilspy it's look more performant

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I'm not sure I understand the reasons why `Array.init` would be faster than array CE because the array is only 8 elements long. Any ideas?

**Comment by AviAvni** [comment]
Sorry I missed the 1 step

**Comment by AviAvni** [comment]
if I add +1 in
https://github.com/AviAvni/BinaryTrees/blob/patch-1/BinaryTrees/Program.fs#L41
then the result is almost the same
image

**Comment by vasily-kirichenko** [comment]
OK, I'm closing it. Thanks anyway :)

**Pull request closed without merging**
